service: consultaplaca

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 6
  # stage: dev
  region: us-east-1
  #profile: devProfile # https://serverless.com/framework/docs/providers/aws/guide/credentials#using-aws-profiles
  # environment:
  #   HTTP_PROXY: http://191.7.192.143:8080

functions:
  placa:
    handler: handler.consultaPlaca
    events:
      - http:
          method: GET
          path: placa/{placa}
          cors:
            origin: "*"

package:
  exclude:
    - .git/**
    - .serverless/**
    - .DS_Store
    - placas/**
    - README.md
    - "*.png"
    - LICENSE.md
    - Makefile
    - package.json
    - yarn.lock

plugins:
  - serverless-offline
